version: '3'
services:
  db:
    image: mysql:5.7.28
    networks:
      - voice-web
    container_name: db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=voiceweb
      - MYSQL_USER=voicecommons
      - MYSQL_PASSWORD=voicecommons
      - MYSQL_ROOT_PASSWORD=voicewebroot
    command: mysqld --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    ports:
      - 3306:3306
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    networks:
      - voice-web
  s3proxy:
    image: andrewgaul/s3proxy
    container_name: s3proxy
    ports:
      - 9001:80
    networks:
      - voice-web
    environment:
      - S3PROXY_AUTHORIZATION=none
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: web
    links:
      - db
      - redis
    volumes:
      - .:/code
    environment:
      - DOTENV_CONFIG_PATH=/code/.env-local-docker
    networks:
      - voice-web
    ports:
      - 9000:9000
    command: bash -c "/code/docker/wait-for-it.sh s3proxy:80 -- /code/docker/prepare_s3.sh && yarn && yarn start"
  redis-web:
    image: rediscommander/redis-commander
    environment:
      REDIS_HOST: "192.168.1.170"
      REDIS_PASSWORD: "0a5b65ebf75b218a0a99022e209ac67acbc3c0920ae76b857ee8398f680f4c68"
      REDIS_USERNAME: ""
      REDIS_DB: "voice"
    ports:
      - 8999:8081
networks:
  voice-web:
